[package]
name = "truss-rs"
version = "0.1.0"
authors = ["Chris McComb <ccmcc2012@gmail.com>"]
edition = "2018"
keywords = ["truss", "structural-analysis", "engineering"]
categories = ["mathematics", "science", "simulation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
